# Generated by Django 3.1.1 on 2021-02-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201006_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('Webapp', 'Webapp'), ('DS', 'Data Science'), ('Courses', 'Courses')], default=str, max_length=7),
            preserve_default=False,
        ),
    ]
