# Generated by Django 3.1.1 on 2021-02-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
    ]
