# Generated by Django 3.1.1 on 2021-02-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Webapp', 'Webapp'), ('DS', 'Data Science'), ('Courses', 'Courses')], default='None', max_length=7),
        ),
    ]
